spring.application.name=duck-store-service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5455/duckstore
spring.datasource.username=admin
spring.datasource.password=pass1234
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
logging.level.org.flywaydb=DEBUG

