CREATE TABLE ducks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color VARCHAR(16)    NOT NULL,
    size  VARCHAR(16)    NOT NULL,
    price      NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    quantity   INTEGER        NOT NULL CHECK (quantity >= 0),
    deleted    BOOLEAN        NOT NULL DEFAULT FALSE
);

-- Merge invariant: at most one LIVE duck per (color, size, price).
-- Logically deleted rows are excluded, so they stay in the table without blocking new ducks.
CREATE UNIQUE INDEX uk_duck_live ON ducks (color, size, price) WHERE deleted = FALSE;
